/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package equipoverde.reservascoches.vista;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USUARIO
 */
public class VentanaClientes extends javax.swing.JFrame {

    String nomArchivo = "listadoDeportistas.dat";
    controladorClientes = new ControladorBDOUsuarios();
    
    String[] nomColumnas = {"NOMBRE",
        "DEPORTE",
        "AÑO NAC.",
        "ALTURA"};
    Object[][] matrizDatos = {
//        {"Carolina Marín", "Bádminton", 1993, 1.72},
//        {"Pau Gasol", "Baloncesto", 1980, 2.15},
//        {"Rafa Nadal", "Tenis", 1986, 1.85},
    };
    
    
    DefaultTableModel dtm = new DefaultTableModel(matrizDatos, nomColumnas);
    
    /**
     * Creates new form VentanaMiniAgenda
     */
    public VentanaClientes() {
        initComponents();
        
        dtm = new DefaultTableModel(matrizDatos, nomColumnas) {

            //para impedir edición de las celdas

            @Override

            public boolean isCellEditable(int fila, int columna) {

                return false;

            }

        };
        // Establecimiento de los datos a la tabla

        jDatos.setModel(dtm);

        

        // Configuración del tipo de selección de la tabla

        jDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        

        // Ajuste de anchos

        jDatos.getColumn("NOMBRE").setPreferredWidth(260);

        jDatos.getColumn("DEPORTE").setPreferredWidth(160);

        jDatos.getColumn("AÑO NAC.").setPreferredWidth(100);

        jDatos.getColumn("ALTURA").setPreferredWidth(200);

        

        // Carga de los datos iniciales salvados previamente en fichero
        
//        miniAgenda.cargarArchivoBin(nomArchivo);
        //listadoDeportistas.dat

        

        // Mostrar los datos del TreeSet en la tabla

        actualizaTabla();

    }
        
        
    
    
    
    
    private void actualizaTabla() {
        //miniAgenda.añadir(new Deportista("Ana","Futbol",2011, 1.76f)); // registro de ejemplo directo
        matrizDatos = controladorClientes.convertirAMatrizObject();
        dtm = new DefaultTableModel(matrizDatos, nomColumnas) {
            //para impedir edición de las celdas
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        jDatos.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
