/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorBDOUsuarios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class UsuariosAplicacion extends javax.swing.JFrame {

    String nomArchivo = "listadoUsuarios.dat";

    ControladorBDOUsuarios ctrlBDO = new ControladorBDOUsuarios();
    String[] nomColumnas = {"NOMBRE", "CONTRASEÑA", "PERMISOS"};
    Object[][] matrizDatos;

    DefaultTableModel dtm = new DefaultTableModel(matrizDatos, nomColumnas);

    /**
     * Creates new form MiniAgenda
     */
    public UsuariosAplicacion() {
        initComponents();
//        actualizaTabla();

    }


//    private void actualizaTabla() {
//        int id = 0;
//        //agenda.a�adir(new Contacto("Ana","S�nchez","999333888", "ana@gmail.com"));
//        matrizDatos = ctrlBDO.obtenerTodo();
//        dtm = new DefaultTableModel(matrizDatos, nomColumnas);
////        dtm = new DefaultTableModel(matrizDatos, nomColumnas) {
////            //para impedir edici�n de las celdas
////            @Override
////            public boolean isCellEditable(int fila, int columna) {
////                return false;
////            }
////        };
//        tDatos.setModel(dtm);
////        tDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
////        tDatos.getColumn("NOMBRE").setPreferredWidth(260);
////        tDatos.getColumn("DEPORTE").setPreferredWidth(160);
////        tDatos.getColumn("A�O NAC.").setPreferredWidth(100);
////        tDatos.getColumn("ALTURA").setPreferredWidth(100);
//
//    }
<<<<<<< HEAD
    private void actualizaTabla() {
        int id = 0;
        //agenda.a�adir(new Contacto("Ana","S�nchez","999333888", "ana@gmail.com"));
 //       matrizDatos = ctrlBDO.obtenerTodo();
        dtm = new DefaultTableModel(matrizDatos, nomColumnas);
//        dtm = new DefaultTableModel(matrizDatos, nomColumnas) {
//            //para impedir edici�n de las celdas
//            @Override
//            public boolean isCellEditable(int fila, int columna) {
//                return false;
//            }
//        };
        tDatos.setModel(dtm);
//        tDatos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
//        tDatos.getColumn("NOMBRE").setPreferredWidth(260);
//        tDatos.getColumn("DEPORTE").setPreferredWidth(160);
//        tDatos.getColumn("A�O NAC.").setPreferredWidth(100);
//        tDatos.getColumn("ALTURA").setPreferredWidth(100);

    }
=======
>>>>>>> a09b4d0727a9734e21e90f524f93a9441a83b094

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JTextField();
        chVaciar = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        bVaciar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        bAñadir = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bGuardarDeFichero = new javax.swing.JButton();
        bCargarDeFichero = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bBorrarPorID = new javax.swing.JButton();
        bBorrarTodo = new javax.swing.JButton();
        bBorrarPorNombre = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MINIAGENDA DE DEPORTISTAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nombre:");

        jLabel2.setText("Contraseña:");

        tfNombre.setToolTipText("");
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfContraseña.setToolTipText("");

        chVaciar.setText("Vaciar después de añadir");
        chVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chVaciarActionPerformed(evt);
            }
        });

        jLabel3.setText("Permisos:");

        bVaciar.setText("Vaciar campos");
        bVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVaciarActionPerformed(evt);
            }
        });

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        bAñadir.setText("Añadir");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Admin");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContraseña)
                            .addComponent(tfNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chVaciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVaciar)
                        .addGap(8, 8, 8)
                        .addComponent(bAñadir)
                        .addGap(18, 18, 18)
                        .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVaciar)
                    .addComponent(chVaciar)
                    .addComponent(bActualizar)
                    .addComponent(bAñadir))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tDatos.setToolTipText("");
        tDatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bGuardarDeFichero.setText("Guardar en fichero");
        bGuardarDeFichero.setPreferredSize(new java.awt.Dimension(125, 23));
        bGuardarDeFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarDeFicheroActionPerformed(evt);
            }
        });

        bCargarDeFichero.setText("Cargar de fichero");
        bCargarDeFichero.setPreferredSize(new java.awt.Dimension(125, 23));
        bCargarDeFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarDeFicheroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bGuardarDeFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCargarDeFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardarDeFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCargarDeFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bBorrarPorID.setText("Borrar seleccionado");
        bBorrarPorID.setPreferredSize(new java.awt.Dimension(125, 23));
        bBorrarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarPorIDActionPerformed(evt);
            }
        });

        bBorrarTodo.setText("Borrar todo");
        bBorrarTodo.setPreferredSize(new java.awt.Dimension(125, 23));
        bBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarTodoActionPerformed(evt);
            }
        });

        bBorrarPorNombre.setText("Borrar por nombre");
        bBorrarPorNombre.setPreferredSize(new java.awt.Dimension(125, 23));
        bBorrarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarPorNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bBorrarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bBorrarPorID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrarPorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBorrarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bCerrar.setBackground(new java.awt.Color(255, 101, 101));
        bCerrar.setText("CERRAR");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(bCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCerrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chVaciarActionPerformed
        tfNombre.setText("");
        tfContraseña.setText("");
<<<<<<< HEAD
    //    tfPermisos.setText("");
=======
>>>>>>> a09b4d0727a9734e21e90f524f93a9441a83b094
    }//GEN-LAST:event_chVaciarActionPerformed

    private void bCargarDeFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarDeFicheroActionPerformed

//        actualizaTabla(miniagendaBDR);
    }//GEN-LAST:event_bCargarDeFicheroActionPerformed


    private void bBorrarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarPorIDActionPerformed
        int id;
        id = tDatos.getSelectedRow();

        if (id >= 0) {
           
            String nombre = (String) matrizDatos[id][0];

            ctrlBDO.borrar(nombre);
//            actualizaTabla();
        } else
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un registro.");
    }//GEN-LAST:event_bBorrarPorIDActionPerformed

    private void bGuardarDeFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarDeFicheroActionPerformed
//        miniAgenda.guardarArchivoBin(nomArchivo);
    }//GEN-LAST:event_bGuardarDeFicheroActionPerformed

    private void bBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarTodoActionPerformed
        int resp;

        // tipo 0 : s�, no
        resp = JOptionPane.showConfirmDialog(rootPane, "¿Estás seguro de eliminar todo?", "Confirmar", 0);
        // si se ha contestado S� = 0
        if (resp == 0) {
            
            ctrlBDO.vaciar();
//            actualizaTabla();
        }


    }//GEN-LAST:event_bBorrarTodoActionPerformed

    private void bBorrarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarPorNombreActionPerformed
        String nombre;
        boolean borrado = false;
<<<<<<< HEAD
        nombre = JOptionPane.showInputDialog(rootPane, "Introduce el nombre y apellido exacto del deportista a borrar:");

   //     borrado = ctrlBDO.borrar(nombre);
        actualizaTabla();
=======
        nombre = JOptionPane.showInputDialog(rootPane, "Introduce el nombre del usuario a borrar:");
//
//        borrado = ctrlBDO.borrar(nombre);
//        actualizaTabla();
>>>>>>> a09b4d0727a9734e21e90f524f93a9441a83b094
        if (borrado)
            System.out.println("Borrado");
        else
            JOptionPane.showMessageDialog(rootPane, "No existe dicho deportista.");
    }//GEN-LAST:event_bBorrarPorNombreActionPerformed

    private void bVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVaciarActionPerformed
        tfNombre.setText("");
        tfContraseña.setText("");
<<<<<<< HEAD
  //      tfPermisos.setText("");
=======
>>>>>>> a09b4d0727a9734e21e90f524f93a9441a83b094
    }//GEN-LAST:event_bVaciarActionPerformed

    private void tDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDatosMouseClicked
        int id;
        String nombre, contraseña, permisos;

        id = tDatos.getSelectedRow();

        if (id >= 0) {
            nombre = (String) matrizDatos[tDatos.getSelectedRow()][0];
            contraseña = (String) matrizDatos[tDatos.getSelectedRow()][1];
            permisos = (String) matrizDatos[tDatos.getSelectedRow()][2];
            tfNombre.setText(nombre);
            tfContraseña.setText(contraseña);
<<<<<<< HEAD
    //        tfPermisos.setText(permisos);
=======
>>>>>>> a09b4d0727a9734e21e90f524f93a9441a83b094
        }
    }//GEN-LAST:event_tDatosMouseClicked

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        int id;
        String nomAux;

        // si est� vac�o el campo nombre, necesario para cualquier inserci�n / actualizaci�n
        if (tfNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo nombre no puede estar vac�o.", "No a�adido", HEIGHT);
        } else {

            // tomamos el registro seleccionado para borrarlo antes de a�adir los datos en los campos de texto
            id = tDatos.getSelectedRow();
            if (id >= 0) {
                nomAux = (String) matrizDatos[tDatos.getSelectedRow()][0];
                ctrlBDO.borrar(nomAux);
                // se a�ade a la agenda un nuevo deportista a partir de los datos de los campos de texto
<<<<<<< HEAD
  //              ctrlBDO.añadir(tfNombre.getText(), tfContraseña.getText(), tfPermisos.getText());
                actualizaTabla();
=======
//                ctrlBDO.añadir(tfNombre.getText(), tfContraseña.getText(), tfPermisos.getText());
//                actualizaTabla();
>>>>>>> a09b4d0727a9734e21e90f524f93a9441a83b094
                if (chVaciar.isSelected()) {
                    tfNombre.setText("");
                    tfContraseña.setText("");
                    
                }
            }
        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        if (tfContraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo nombre no puede estar vac�o.", "No a�adido", HEIGHT);
        } else {
            // se a�ade a la agenda un nuevo deportista a partir de los datos de los campos de texto

<<<<<<< HEAD
    //        ctrlBDO.añadir(tfNombre.getText(), tfContraseña.getText(), tfPermisos.getText());
            actualizaTabla();
=======
//            ctrlBDO.añadir(tfNombre.getText(), tfContraseña.getText(), tfPermisos.getText());
//            actualizaTabla();
>>>>>>> a09b4d0727a9734e21e90f524f93a9441a83b094
        }
    }//GEN-LAST:event_bAñadirActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCerrarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bBorrarPorID;
    private javax.swing.JButton bBorrarPorNombre;
    private javax.swing.JButton bBorrarTodo;
    private javax.swing.JButton bCargarDeFichero;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bGuardarDeFichero;
    private javax.swing.JButton bVaciar;
    private javax.swing.JCheckBox chVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tDatos;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
